name: pattern
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - jupyterlab
  - ipykernel
  - statsmodels
  - requests
  - pip
  - pip:
      - hmmlearn
      - yfinance
      - fredapi
      - nbconvert
      - gymnasium
      - stable-baselines3
      - torch
      - transformers
      - gnews
      - newspaper3k
      - beautifulsoup4
